### ISSUE TITLE
Can't add integration

### ISSUE THREAD

**Issue by araujojr82** [tiorac/ha-subsonic#2]
First of all, thank you for creating this integration, this is something that I've been searching for a while.

It would be nice if you could add a how-to install guide.

The integration was install using HACS, after adding your github as a custom repository.

I'm trying to configure  the integration to my HA, but I'm getting this error:
![image](https://github.com/user-attachments/assets/3fcb62c2-f73c-41b1-b7bc-ad5110da4732)

Things I've tried so far with no luck:
1) with or without 
http://192.168.50.2:4533
192.168.50.2:4533

2) using https:// through a reverse proxy
https://navidrome.mydomain.com

I'm always getting the same error "Unknown error occurred"

**Comment by tiorac** [comment]
There was a change in Home Assistant that started generating an error in the configuration workflow.

I made the correction, try updating the plugin and configuring it again, the data seems correct, it can be directly by IP or via reverse proxy, as long as HA can access it there is no problem.
